// Generated by CoffeeScript 1.8.0
var $, $menubar, itemClickE;

$ = require("jquery");

$menubar = $("#menubar");

$menubar.find(".menu").each(function() {
  var $menu, visibleP;
  $menu = $(this);
  visibleP = $menu.find(".menu-icon").asEventStream("click").scan(false, function(state) {
    return !state;
  });
  return visibleP.onValue(function(visible) {
    return $menu.find("ul").toggle(visible);
  });
});

itemClickE = $menubar.find(".menu li").asEventStream("click").map(function(e) {
  return $(e.target);
});

itemClickE.onValue(function(el) {
  return el.closest(".menu ul").hide();
});

module.exports = {
  itemClickE: function(menuId) {
    return itemClickE.map(function(el) {
      return el.attr("id");
    }).filter(function(id) {
      return id === menuId;
    });
  }
};
